//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studnt_ClientSide.ServiceStudent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Students", Namespace="http://schemas.datacontract.org/2004/07/WCF_StudentServerSide")]
    [System.SerializableAttribute()]
    public partial class Students : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodemasarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codemasar {
            get {
                return this.CodemasarField;
            }
            set {
                if ((object.ReferenceEquals(this.CodemasarField, value) != true)) {
                    this.CodemasarField = value;
                    this.RaisePropertyChanged("Codemasar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_name {
            get {
                return this.First_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_nameField, value) != true)) {
                    this.First_nameField = value;
                    this.RaisePropertyChanged("First_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_name {
            get {
                return this.Last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_nameField, value) != true)) {
                    this.Last_nameField = value;
                    this.RaisePropertyChanged("Last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Major {
            get {
                return this.MajorField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorField, value) != true)) {
                    this.MajorField = value;
                    this.RaisePropertyChanged("Major");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
    [System.SerializableAttribute()]
    public partial class ArgumentFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
    [System.SerializableAttribute()]
    public partial class SqlConnectionFailed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teachers", Namespace="http://schemas.datacontract.org/2004/07/WCF_StudentServerSide")]
    [System.SerializableAttribute()]
    public partial class Teachers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodemasarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Teacher_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codemasar {
            get {
                return this.CodemasarField;
            }
            set {
                if ((object.ReferenceEquals(this.CodemasarField, value) != true)) {
                    this.CodemasarField = value;
                    this.RaisePropertyChanged("Codemasar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Teacher_id {
            get {
                return this.Teacher_idField;
            }
            set {
                if ((this.Teacher_idField.Equals(value) != true)) {
                    this.Teacher_idField = value;
                    this.RaisePropertyChanged("Teacher_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsuccessfullLoginFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
    [System.SerializableAttribute()]
    public partial class UnsuccessfullLoginFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStudent.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.ArgumentFault), Action="http://tempuri.org/IService1/GetStudentArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.SqlConnectionFailed), Action="http://tempuri.org/IService1/GetStudentSqlConnectionFailedFault", Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        Studnt_ClientSide.ServiceStudent.Students GetStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Students> GetStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addgrades", ReplyAction="http://tempuri.org/IService1/AddgradesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.ArgumentFault), Action="http://tempuri.org/IService1/AddgradesArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.SqlConnectionFailed), Action="http://tempuri.org/IService1/AddgradesSqlConnectionFailedFault", Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        void Addgrades(Studnt_ClientSide.ServiceStudent.Students student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addgrades", ReplyAction="http://tempuri.org/IService1/AddgradesResponse")]
        System.Threading.Tasks.Task AddgradesAsync(Studnt_ClientSide.ServiceStudent.Students student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.UnsuccessfullLoginFault), Action="http://tempuri.org/IService1/LoginUnsuccessfullLoginFaultFault", Name="UnsuccessfullLoginFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.ArgumentFault), Action="http://tempuri.org/IService1/LoginArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.SqlConnectionFailed), Action="http://tempuri.org/IService1/LoginSqlConnectionFailedFault", Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        Studnt_ClientSide.ServiceStudent.Teachers Login(string codemasar, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Teachers> LoginAsync(string codemasar, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.ArgumentFault), Action="http://tempuri.org/IService1/UpdateArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.SqlConnectionFailed), Action="http://tempuri.org/IService1/UpdateSqlConnectionFailedFault", Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        void Update(Studnt_ClientSide.ServiceStudent.Students students);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Studnt_ClientSide.ServiceStudent.Students students);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.ArgumentFault), Action="http://tempuri.org/IService1/DeleteArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.SqlConnectionFailed), Action="http://tempuri.org/IService1/DeleteSqlConnectionFailedFault", Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        Studnt_ClientSide.ServiceStudent.Students Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete", ReplyAction="http://tempuri.org/IService1/DeleteResponse")]
        System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Students> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/List", ReplyAction="http://tempuri.org/IService1/ListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.ArgumentFault), Action="http://tempuri.org/IService1/ListArgumentFaultFault", Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        [System.ServiceModel.FaultContractAttribute(typeof(Studnt_ClientSide.ServiceStudent.SqlConnectionFailed), Action="http://tempuri.org/IService1/ListSqlConnectionFailedFault", Name="SqlConnectionFailed", Namespace="http://schemas.datacontract.org/2004/07/Masar_DataBase")]
        Studnt_ClientSide.ServiceStudent.Students[] List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/List", ReplyAction="http://tempuri.org/IService1/ListResponse")]
        System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Students[]> ListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Studnt_ClientSide.ServiceStudent.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Studnt_ClientSide.ServiceStudent.IService1>, Studnt_ClientSide.ServiceStudent.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Studnt_ClientSide.ServiceStudent.Students GetStudent(int id) {
            return base.Channel.GetStudent(id);
        }
        
        public System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Students> GetStudentAsync(int id) {
            return base.Channel.GetStudentAsync(id);
        }
        
        public void Addgrades(Studnt_ClientSide.ServiceStudent.Students student) {
            base.Channel.Addgrades(student);
        }
        
        public System.Threading.Tasks.Task AddgradesAsync(Studnt_ClientSide.ServiceStudent.Students student) {
            return base.Channel.AddgradesAsync(student);
        }
        
        public Studnt_ClientSide.ServiceStudent.Teachers Login(string codemasar, string password) {
            return base.Channel.Login(codemasar, password);
        }
        
        public System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Teachers> LoginAsync(string codemasar, string password) {
            return base.Channel.LoginAsync(codemasar, password);
        }
        
        public void Update(Studnt_ClientSide.ServiceStudent.Students students) {
            base.Channel.Update(students);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Studnt_ClientSide.ServiceStudent.Students students) {
            return base.Channel.UpdateAsync(students);
        }
        
        public Studnt_ClientSide.ServiceStudent.Students Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Students> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public Studnt_ClientSide.ServiceStudent.Students[] List() {
            return base.Channel.List();
        }
        
        public System.Threading.Tasks.Task<Studnt_ClientSide.ServiceStudent.Students[]> ListAsync() {
            return base.Channel.ListAsync();
        }
    }
}
